KS-19-4
vvaganov/KotlinSprint pull request #96
Opened 2024-06-27 11:13 UTC by vvaganov

2024-06-28 08:00 UTC, vvaganov commented
Исправил на версию с Null

2024-06-28 21:50 UTC, ievetrovdev requested changes

2024-06-28 21:51 UTC, ievetrovdev requested changes

2024-06-29 05:11 UTC, vvaganov commented on src/main/kotlin/lesson19/lesson19-task4.kt
> +    BLUE {
исправлено, сразу не доходит просто:))

2024-06-29 05:12 UTC, vvaganov commented on src/main/kotlin/lesson19/lesson19-task4.kt
> +        println("Выстрел партоном $patronType, нанесенный ущерб - ${patronType?.getDamageCaused()} ")
Сделано

2024-06-29 23:00 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-07-01 04:25 UTC, merged